/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author GhOsT
 */
public class NewFlight extends javax.swing.JFrame {

    /**
     * Creates new form NewFlight
     */
    public NewFlight() {
        initComponents();
        this.setLocationRelativeTo(null);
           try {
            autoID();
        } catch (SQLException ex) {
            Logger.getLogger(NewAddCustomer1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

     Connection con;
    PreparedStatement pt;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flightArrival = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        flightDeparture = new javax.swing.JTextField();
        flightDestination = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        flightSource = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        fID = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        flightPrice = new javax.swing.JTextField();
        flightDate = new com.toedter.calendar.JDateChooser();
        flightName = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 480));
        setUndecorated(true);
        getContentPane().setLayout(null);
        getContentPane().add(flightArrival);
        flightArrival.setBounds(230, 310, 220, 30);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setText("Arrival");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 310, 58, 24);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setText("Departure");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 270, 87, 24);

        flightDeparture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightDepartureActionPerformed(evt);
            }
        });
        getContentPane().add(flightDeparture);
        flightDeparture.setBounds(230, 270, 220, 30);

        flightDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mumbai", "Banglore", "Delhi", "Chennai", "Cochi" }));
        getContentPane().add(flightDestination);
        flightDestination.setBounds(230, 230, 220, 30);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setText("Destination");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 230, 99, 24);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setText("Source");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 190, 62, 24);

        flightSource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mumbai", "Banglore", "Delhi", "Chennai", "Cochi" }));
        getContentPane().add(flightSource);
        flightSource.setBounds(230, 190, 220, 30);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("Flight ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 140, 80, 40);

        fID.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        fID.setText("Flight ID");
        getContentPane().add(fID);
        fID.setBounds(280, 150, 80, 24);

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setText("Flight Name");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(480, 190, 105, 24);

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setText("Date");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(540, 240, 50, 24);

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setText("Price");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(530, 300, 58, 24);
        getContentPane().add(flightPrice);
        flightPrice.setBounds(610, 300, 220, 30);
        getContentPane().add(flightDate);
        flightDate.setBounds(610, 240, 220, 30);
        getContentPane().add(flightName);
        flightName.setBounds(610, 190, 220, 30);

        jButton2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton2.setText("X");
        jButton2.setContentAreaFilled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(870, 30, 40, 30);

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton1.setText("Register");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(430, 360, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MyPc\\Desktop\\AccioProjects\\Project\\FLight\\11.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 950, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

        public void autoID() throws SQLException{
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","");
            
            Statement s =con.createStatement();
            ResultSet rs=s.executeQuery("select MAX(FlightID) from flight");
            rs.next();
            rs.getString("MAX(FlightID)");
            
            if(rs.getString("MAX(FlightID)")==null){
              fID.setText("111");
              
            }
            else{
               long id =Long.parseLong(rs.getString("MAX(FlightID)"));
               id++;
               fID.setText(String.format("%03d", id));
    
            }

        }
        catch (ClassNotFoundException ex) {
            Logger.getLogger(NewFlight.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    private void flightDepartureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightDepartureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightDepartureActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id=fID.getText();
        String source= flightSource.getSelectedItem().toString();
        String destination=flightDestination.getSelectedItem().toString();
        String departure=flightDeparture.getText();
        String arrival=flightArrival.getText();
        String name=flightName.getText();
        
        DateFormat dt=new SimpleDateFormat("yyyy-MM-dd");
        String date=dt.format(flightDate.getDate());
        
       String price=flightPrice.getText();
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","");
            pt = con.prepareStatement("insert into flight(FlightID,FlightName,FlightSource,FlightDestination,FlightDeparture,FlightArrival,FlightDate,FlightPrice)values(?,?,?,?,?,?,?,?)");
            pt.setString(1,id);
            pt.setString(2,name);
            pt.setString(3,source);
            pt.setString(4,destination);
            pt.setString(5,departure);
            pt.setString(6,arrival);
            pt.setString(7,date);
            pt.setString(8,price);
           
            pt.executeUpdate();
           JOptionPane.showMessageDialog(null,"Records UPdates Successfully");

            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewAddCustomer1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewAddCustomer1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,255,255), 2, true));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        jButton2.setBorder(null);
    }//GEN-LAST:event_jButton2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewFlight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fID;
    private javax.swing.JTextField flightArrival;
    private com.toedter.calendar.JDateChooser flightDate;
    private javax.swing.JTextField flightDeparture;
    private javax.swing.JComboBox<String> flightDestination;
    private javax.swing.JTextField flightName;
    private javax.swing.JTextField flightPrice;
    private javax.swing.JComboBox<String> flightSource;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
