/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author GhOsT
 */
public class UserNew extends javax.swing.JFrame {

    /**
     * Creates new form UserNew
     */
    public UserNew() {
        initComponents();
        this.setLocationRelativeTo(null);
           try {
            autoID();
        } catch (SQLException ex) {
            Logger.getLogger(NewAddCustomer1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    Connection con;
    PreparedStatement pt;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
        public void autoID() throws SQLException{
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","");
            
            Statement s =con.createStatement();
            ResultSet rs=s.executeQuery("select MAX(ID) from user");
            rs.next();
            rs.getString("MAX(ID)");
            
            if(rs.getString("MAX(ID)")==null){
              userID1.setText("111");
              
            }
            else{
               long id =Long.parseLong(rs.getString("MAX(ID)"));
               id++;
               userID1.setText(String.format("%03d", id));
               
                
            }

        }
        catch (ClassNotFoundException ex) {
            Logger.getLogger(NewAddCustomer1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LastName1 = new javax.swing.JTextField();
        FirstName1 = new javax.swing.JTextField();
        userID1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        UserName1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Password1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 480));
        setUndecorated(true);
        getContentPane().setLayout(null);

        LastName1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(LastName1);
        LastName1.setBounds(390, 212, 190, 30);

        FirstName1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FirstName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstName1ActionPerformed(evt);
            }
        });
        getContentPane().add(FirstName1);
        FirstName1.setBounds(390, 172, 190, 30);

        userID1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        userID1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userID1.setText("UserID");
        getContentPane().add(userID1);
        userID1.setBounds(390, 130, 190, 24);

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setText("Password");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(200, 290, 86, 24);

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setText("UserName");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(200, 250, 92, 24);

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setText("LastName");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(200, 210, 88, 24);

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel7.setText("USER DETAILS");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(290, 70, 190, 32);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setText("FirstName");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 170, 90, 24);

        jButton4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton4.setText("Register");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(410, 340, 110, 40);

        jButton3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(270, 340, 110, 40);

        UserName1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserName1ActionPerformed(evt);
            }
        });
        getContentPane().add(UserName1);
        UserName1.setBounds(390, 250, 190, 30);

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel11.setText("UserID");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(210, 130, 80, 24);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("X");
        jButton2.setContentAreaFilled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(870, 20, 40, 30);

        Password1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Password1);
        Password1.setBounds(390, 290, 190, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MyPc\\Desktop\\AccioProjects\\Project\\FLight\\11.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 950, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String id=userID1.getText();
        String firstName=FirstName1.getText();
        String lastName=LastName1.getText();
        String userName=UserName1.getText();
        String password=Password1.getText();


        if(userName.isEmpty()||password.isEmpty()||firstName.isEmpty()||lastName.isEmpty()){
            JOptionPane.showMessageDialog(this,"Invalid Response");
        }
        else{
                 try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","");
            pt = con.prepareStatement("insert into user(ID,FirstName,LastName,UserName,Password)values(?,?,?,?,?)");
            pt.setString(1,id);
            pt.setString(2,firstName);
            pt.setString(3,lastName);
            pt.setString(4,userName);
            pt.setString(5,password);

            pt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Records UPdates Successfully");

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewAddCustomer1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewAddCustomer1.class.getName()).log(Level.SEVERE, null, ex);
        }
        }


   
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void UserName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserName1ActionPerformed

    private void FirstName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstName1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,255,255), 2, true));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        jButton2.setBorder(null);
    }//GEN-LAST:event_jButton2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FirstName1;
    private javax.swing.JTextField LastName1;
    private javax.swing.JPasswordField Password1;
    private javax.swing.JTextField UserName1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel userID1;
    // End of variables declaration//GEN-END:variables
}
